IMAGE_INSTALL:append = " picamera2"
IMAGE_INSTALL:append = " python3-picamera2"

IMAGE_INSTALL:append = " picamera2 picamera2-dbg picamera2-dev"

IMAGE_INSTALL:append = " v4l2loopbackpackages" --- no need

-------------------------------------------------------------------------------------------------
Need to include in local.conf