# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-face_blur"
BBFILE_PATTERN_meta-face_blur = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-face_blur = "6"

LAYERDEPENDS_meta-face_blur = "core"
LAYERSERIES_COMPAT_meta-face_blur = "scarthgap"