/* 
 * File:	D:\Sigma studio session\Sigma studio session_DiffDXESchematic_0_PARAM.h
 * Created:	Thursday, 24 October 2024 18:05 PM
 * Description:	DiffDXESchematic_0 parameter RAM definitions.
 * 
 * This software is distributed in the hope that it will be useful, 
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 * This software may only be used to program products purchased from 
 * Analog Devices for incorporation by you into audio products that 
 * are intended for resale to audio product end users.This software 
 * may not be distributed whole or in any part to third parties. 
 * 
 * Copyright © 2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __SIGMA STUDIO SESSION_DIFFDXESCHEMATIC_0_PARAM_H__
#define __SIGMA STUDIO SESSION_DIFFDXESCHEMATIC_0_PARAM_H__




/* Module Mute_0 - Mute (No Slew) */
#define MOD_MUTE_0_COUNT         1
#define MOD_MUTE_0_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_0_MUTE_ADDR     12
#define MOD_MUTE_0_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_0_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_0_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_1 - Mute (No Slew) */
#define MOD_MUTE_1_COUNT         1
#define MOD_MUTE_1_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_1_MUTE_ADDR     11
#define MOD_MUTE_1_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_1_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_1_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module ParametricEqNoSlew_0 - Parametric EQ */
#define MOD_PARAMETRICEQNOSLEW_0_COUNT              40
#define MOD_PARAMETRICEQNOSLEW_0_SCHEMATIC          "DiffDXESchematic_0"
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B0_ADDR     15
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B1_ADDR     14
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B2_ADDR     13
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A1_ADDR     17
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A2_ADDR     16
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE0_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B0_ADDR     20
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B1_ADDR     19
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B2_ADDR     18
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A1_ADDR     22
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A2_ADDR     21
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE1_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B0_ADDR     25
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B1_ADDR     24
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B2_ADDR     23
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A1_ADDR     27
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A2_ADDR     26
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE2_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B0_ADDR     30
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B1_ADDR     29
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B2_ADDR     28
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A1_ADDR     32
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A2_ADDR     31
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE3_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B0_ADDR     35
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B1_ADDR     34
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B2_ADDR     33
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A1_ADDR     37
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A2_ADDR     36
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE4_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B0_ADDR     40
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B1_ADDR     39
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B2_ADDR     38
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A1_ADDR     42
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A2_ADDR     41
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE5_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B0_ADDR     45
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B1_ADDR     44
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B2_ADDR     43
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A1_ADDR     47
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A2_ADDR     46
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE6_A2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B0_ADDR     50
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B0_FIXPT    0x3F800000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B0_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B0_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B1_ADDR     49
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B2_ADDR     48
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_B2_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A1_ADDR     52
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A1_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A1_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A1_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A2_ADDR     51
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A2_FIXPT    0x00000000
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A2_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_PARAMETRICEQNOSLEW_0_STAGE7_A2_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_2 - Mute (No Slew) */
#define MOD_MUTE_2_COUNT         1
#define MOD_MUTE_2_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_2_MUTE_ADDR     10
#define MOD_MUTE_2_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_2_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_2_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_3 - Mute (No Slew) */
#define MOD_MUTE_3_COUNT         1
#define MOD_MUTE_3_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_3_MUTE_ADDR     9
#define MOD_MUTE_3_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_3_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_3_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_4 - Mute (No Slew) */
#define MOD_MUTE_4_COUNT         1
#define MOD_MUTE_4_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_4_MUTE_ADDR     8
#define MOD_MUTE_4_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_4_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_4_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_5 - Mute (No Slew) */
#define MOD_MUTE_5_COUNT         1
#define MOD_MUTE_5_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_5_MUTE_ADDR     7
#define MOD_MUTE_5_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_5_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_5_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_6 - Mute (No Slew) */
#define MOD_MUTE_6_COUNT         1
#define MOD_MUTE_6_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_6_MUTE_ADDR     6
#define MOD_MUTE_6_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_6_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_6_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module Mute_7 - Mute (No Slew) */
#define MOD_MUTE_7_COUNT         1
#define MOD_MUTE_7_SCHEMATIC     "DiffDXESchematic_0"
#define MOD_MUTE_7_MUTE_ADDR     5
#define MOD_MUTE_7_MUTE_FIXPT    0x3F800000
#define MOD_MUTE_7_MUTE_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_MUTE_7_MUTE_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module NxMMixer_0 - NxM Mixer */
#define MOD_NXMMIXER_0_COUNT              1
#define MOD_NXMMIXER_0_SCHEMATIC          "DiffDXESchematic_0"
#define MOD_NXMMIXER_0_GAINARRAY_ADDR     53
#define MOD_NXMMIXER_0_GAINARRAY_FIXPT    0x3F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F8000003F800000
#define MOD_NXMMIXER_0_GAINARRAY_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(0)
#define MOD_NXMMIXER_0_GAINARRAY_TYPE     SIGMASTUDIOTYPE_FLOAT

/* Module WhiteNoise_0 - White Noise */
#define MOD_WHITENOISE_0_COUNT                       2
#define MOD_WHITENOISE_0_SCHEMATIC                   "DiffDXESchematic_0"
#define MOD_WHITENOISE_0_WHITENOISE_ENABLED_ADDR     4
#define MOD_WHITENOISE_0_WHITENOISE_ENABLED_FIXPT    0x3F800000
#define MOD_WHITENOISE_0_WHITENOISE_ENABLED_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_WHITENOISE_0_WHITENOISE_ENABLED_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_WHITENOISE_0_SEED_ADDR                   3
#define MOD_WHITENOISE_0_SEED_FIXPT                  0x0000F771
#define MOD_WHITENOISE_0_SEED_VALUE                  SIGMASTUDIOTYPE_INTEGER_CONVERT(63345)
#define MOD_WHITENOISE_0_SEED_TYPE                   SIGMASTUDIOTYPE_INTEGER

/* Module MonoSwitchNx1_0 - Nx1 Switch */
#define MOD_MONOSWITCHNX1_0_COUNT          1
#define MOD_MONOSWITCHNX1_0_SCHEMATIC      "DiffDXESchematic_0"
#define MOD_MONOSWITCHNX1_0_INDEX_ADDR     70
#define MOD_MONOSWITCHNX1_0_INDEX_FIXPT    0x00000000
#define MOD_MONOSWITCHNX1_0_INDEX_VALUE    SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_MONOSWITCHNX1_0_INDEX_TYPE     SIGMASTUDIOTYPE_INTEGER

/* Module MonoSwitchNx1_1 - Nx1 Switch */
#define MOD_MONOSWITCHNX1_1_COUNT          1
#define MOD_MONOSWITCHNX1_1_SCHEMATIC      "DiffDXESchematic_0"
#define MOD_MONOSWITCHNX1_1_INDEX_ADDR     69
#define MOD_MONOSWITCHNX1_1_INDEX_FIXPT    0x00000000
#define MOD_MONOSWITCHNX1_1_INDEX_VALUE    SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_MONOSWITCHNX1_1_INDEX_TYPE     SIGMASTUDIOTYPE_INTEGER

/* Module WhiteNoise_1 - White Noise */
#define MOD_WHITENOISE_1_COUNT                       2
#define MOD_WHITENOISE_1_SCHEMATIC                   "DiffDXESchematic_0"
#define MOD_WHITENOISE_1_WHITENOISE_ENABLED_ADDR     2
#define MOD_WHITENOISE_1_WHITENOISE_ENABLED_FIXPT    0x3F800000
#define MOD_WHITENOISE_1_WHITENOISE_ENABLED_VALUE    SIGMASTUDIOTYPE_FLOAT_CONVERT(1)
#define MOD_WHITENOISE_1_WHITENOISE_ENABLED_TYPE     SIGMASTUDIOTYPE_FLOAT
#define MOD_WHITENOISE_1_SEED_ADDR                   1
#define MOD_WHITENOISE_1_SEED_FIXPT                  0x0000F771
#define MOD_WHITENOISE_1_SEED_VALUE                  SIGMASTUDIOTYPE_INTEGER_CONVERT(63345)
#define MOD_WHITENOISE_1_SEED_TYPE                   SIGMASTUDIOTYPE_INTEGER

#endif
