# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-drowsiness"
BBFILE_PATTERN_meta-drowsiness = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-drowsiness = "6"

LAYERDEPENDS_meta-drowsiness = "core"
LAYERSERIES_COMPAT_meta-drowsiness = "scarthgap"