# Layer configuration for meta-serdes

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-serdes"
BBFILE_PATTERN_meta-serdes = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-serdes = "7"

# Important: declare Yocto compatibility (Scarthgap release)
LAYERSERIES_COMPAT_meta-serdes = "scarthgap"
